name: Update Rating

on:
  push:
    paths:
      - 'scoreb50.jpg'

permissions:
  contents: write

jobs:
  update-rating:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt install tesseract-ocr
        python -m pip install --upgrade pip
        pip install matplotlib numpy pytesseract pillow opencv-python-headless

    - name: Run graph.py
      run: python history/graph.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add history/rating.csv history/rating.jpg
        git commit -m 'Update rating.csv and rating.jpg'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
